export const rooms = [
  {
    id: 1,
      name: "Single Room",
    type: "Single bed with premium linen",
    price: "500",
    size: "18–22 sq.m.",
    additional1: "Free Wifi",
    additional2: "Compact seating",
    additional3: "Private bathroom with rain shower",
    image:
      "public/singlebed.jpg",
  },
  {
    id: 2,
     name: "Single Room",
    type: "Single bed with premium linen",
    price: "500",
    size: "18–22 sq.m.",
    additional1: "Free Wifi",
    additional2: "Compact seating",
    additional3: "Private bathroom with rain shower",
    image:
     "public/singlebed.jpg",
  },
  {
    id: 3,
   name: "Single Room",
    type: "Single bed with premium linen",
    price: "500",
    size: "18–22 sq.m.",
    additional1: "Free Wifi",
    additional2: "Compact seating",
    additional3: "Private bathroom with rain shower",
   image:
      "public/singlebed.jpg",
  },
  {
    id: 13,
   name: "Single Room",
    type: "Single bed with premium linen",
    price: "500",
    size: "18–22 sq.m.",
    additional1: "Free Wifi",
    additional2: "Compact seating",
    additional3: "Private bathroom with rain shower",
   image:
      "public/singlebed.jpg",
  },
  {
    id: 4,
    name: "Double Room",
    type: "Twin bed",
    price: "800",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Private bathroom with rain shower",
    image:     "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020569/olexandr-ignatov-w72a24brINI-unsplash_1_pvofpl.jpg",
   },
  {
    id: 5,
      name: "Double Room",
    type: "Twin bed",
    price: "800",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Private bathroom with rain shower",
    image:     "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020569/olexandr-ignatov-w72a24brINI-unsplash_1_pvofpl.jpg",
  },
  {
    id: 6,
    name: "Double Room",
    type: "King bed",
    price: "800",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Private bathroom with rain shower",
    image: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020403/227707266_qoqdcw.png",
   },
  {
    id: 7,
    name: "Double Room",
    type: "King bed",
    price: "800",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Private bathroom with rain shower",
    image: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020403/227707266_qoqdcw.png",
  },
  {
    id: 8,
    name: "Double Room",
    type: "King bed",
    price: "1000",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Bathroom with spa bathtub",
    image:
 "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020570/point3d-commercial-imaging-ltd-_Swg04CP0bU-unsplash_uqjdcl.jpg",
  },
  {
    id: 9,
     name: "Double Room",
    type: "King bed",
    price: "1000",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Bathroom with spa bathtub",
    image:
 "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020570/point3d-commercial-imaging-ltd-_Swg04CP0bU-unsplash_uqjdcl.jpg",
   },
  {
    id: 10,
    name: "Double Room",
    type: "King bed",
    price: "1000",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Bathroom with spa bathtub",
    image:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020570/point3d-commercial-imaging-ltd-_Swg04CP0bU-unsplash_uqjdcl.jpg",
   },
   {
    id: 14,
    name: "Double Room",
    type: "King bed",
    price: "1000",
    size: "24–30 sq.m.",
    additional1: "Free Wifi",
    additional2: "Small sitting area",
    additional3: "Bathroom with spa bathtub",
    image:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020570/point3d-commercial-imaging-ltd-_Swg04CP0bU-unsplash_uqjdcl.jpg",
   },
  {
    id: 11,
    name: "Family Room",
    type: "One double bed & One single bed",
    price: "1200",
    size: "32–40 sq.m",
    additional1: "Free Wifi",
    additional2: "Bathroom with spa bathtub",
    additional3: "Generous living space",
    image:       "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020488/pexels-pixabay-276671_ssbzp0.jpg",
 },
  {
    id: 12,
    name: "Family Room",
    type: "One double bed & One single bed",
    price: "1200",
    size: "32–40 sq.m",
    additional1: "Free Wifi",
    additional2: "Bathroom with spa bathtub",
    additional3: "Generous living space",
   
    image:       "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020488/pexels-pixabay-276671_ssbzp0.jpg",
  },
{
    id: 15,
    name: "Family Room",
    type: "One double bed & One single bed",
    price: "1200",
    size: "32–40 sq.m",
    additional1: "Free Wifi",
    additional2: "Bathroom with spa bathtub",
    additional3: "Generous living space",
   
    image:       "https://res.cloudinary.com/dhggmrfe1/image/upload/v1767020488/pexels-pixabay-276671_ssbzp0.jpg",
  },





];
